//sidebar
export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';

//animals
export const GET_ANIMALS_BEGIN = 'GET_ANIMALS_BEGIN';
export const GET_ANIMALS_SUCCESS = 'GET_ANIMALS_SUCCESS';
export const GET_ANIMALS_ERROR = 'GET_ANIMALS_ERROR';
export const GET_SINGLE_ANIMAL_BEGIN = 'GET_SINGLE_ANIMAL_BEGIN';
export const GET_SINGLE_ANIMAL_SUCCESS = 'GET_SINGLE_ANIMAL_SUCCESS';
export const GET_SINGLE_ANIMAL_ERROR = 'GET_SINGLE_ANIMAL_ERROR';
