//sidebar
export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';

//animals
export const GET_ANIMALS_BEGIN = 'GET_ANIMALS_BEGIN';
export const GET_ANIMALS_SUCCESS = 'GET_ANIMALS_SUCCESS';
export const GET_ANIMALS_ERROR = 'GET_ANIMALS_ERROR';
export const GET_SINGLE_ANIMAL_BEGIN = 'GET_SINGLE_ANIMAL_BEGIN';
export const GET_SINGLE_ANIMAL_SUCCESS = 'GET_SINGLE_ANIMAL_SUCCESS';
export const GET_SINGLE_ANIMAL_ERROR = 'GET_SINGLE_ANIMAL_ERROR';

//filters
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const SET_GRIDVIEW = 'SET_GRIDVIEW';
export const SET_LISTVIEW = 'SET_LISTVIEW';
export const UPDATE_SORT = 'UPDATE_SORT';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';